/*******************************************************************************
* FILE NAME: test.hpp                                                          *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     test                                                                     *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _TEST_
#define _TEST_  

class test;

#ifndef _IFRAME_
#include <iframe.hpp>
#endif

class ICanvas;
class IPushButton;
#define INCL_WINSTDCNR
#include <os2.h>

#ifndef _APERSON_
#include "APerson.hpp"
#endif

#ifndef _IMYKYSRT_
#include "imykysrt.h"
#endif

#ifndef _IVBCNR_
#include <ivbcnr.h>
#endif

class IContainerColumn;
template <class Element> class IMyKeySortedSet;
#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ISTRING_
#include <istring.hpp>
#endif

#ifndef _ITIME_
#include <itime.hpp>
#endif

class testConn13;
class testConn14;
class testConn2;
class testConn3;
class testConn4;
#include "test.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for testVBContainerControl1CnrObj
//*****************************************************************************
class testVBContainerControl1CnrObj : public IVBContainerObject {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   testVBContainerControl1CnrObj(APerson& anObject);
   testVBContainerControl1CnrObj(testVBContainerControl1CnrObj& anObject);

   virtual  ~testVBContainerControl1CnrObj();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   IVBContainerObject & refreshFromObject();
   IVBContainerObject & updateToObject();
   testVBContainerControl1CnrObj& operator=(const testVBContainerControl1CnrObj& anObject);
   APerson* realObject() { return &pRealObject; }
;

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   IString Age;
   IString Name;

protected:
private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   APerson & pRealObject;


};   //testVBContainerControl1CnrObj


//*****************************************************************************
// Class definition for test
//*****************************************************************************
class test : public IFrameWindow {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   test(
      unsigned long id = WND_test,
      IWindow* parent = IWindow::desktopWindow(),
      IWindow* owner = 0,
      const IRectangle& rect = defaultFramingSpec(),
      const IFrameWindow::Style& style = IFrameWindow::defaultStyle ( ),
      const char* title = defaultTitle());

   virtual  ~test();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static const IRectangle defaultFramingSpec();
   static IString defaultTitle();
   virtual test & initializePart();
   test * getFrameWindow() { return this; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   ICanvas * iCanvas;
   IPushButton * iPushButton1;
   IVBContainerControl< APerson*, IMyKeySortedSet<APerson*>, testVBContainerControl1CnrObj > * iVBContainerControl1;
   IContainerColumn * iContainerColumn1;
   IContainerColumn * iContainerColumn2;
   IPushButton * iPushButton2;
   IPushButton * iPushButton3;
   IMyKeySortedSet< APerson* > * iMyKeySortedSet1;
   testConn13 * conn13;
   testConn14 * conn14;
   testConn2 * conn2;
   testConn3 * conn3;
   testConn4 * conn4;
   static unsigned long partWindowId;

friend class testConn14;
friend class testConn2;
friend class testConn4;

};   //test


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
