/*******************************************************************************
* FILE NAME: test.h                                                            *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     test                                                                     *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_test
#define WND_test  VBBASEWINDOWID
#endif

#define WNDOFFSET_test_FrameWindow  0
#define WND_test_FrameWindow  WND_test

#define WND_test_Canvas  IC_FRAME_CLIENT_ID

#define WNDOFFSET_test_PushButton1  1
#define WND_test_PushButton1  WND_test + WNDOFFSET_test_PushButton1

#define WNDOFFSET_test_VBContainerControl1  2
#define WND_test_VBContainerControl1  WND_test + WNDOFFSET_test_VBContainerControl1



#define WNDOFFSET_test_PushButton2  3
#define WND_test_PushButton2  WND_test + WNDOFFSET_test_PushButton2

#define WNDOFFSET_test_PushButton3  4
#define WND_test_PushButton3  WND_test + WNDOFFSET_test_PushButton3



